var context={
"selected":"0",
"albums":[
{"name":"Gorrilaz","id":"1","year":"2001","photo":"thumbnails/album1thumbnail.jpg","songs":[
				{ "id": "1", "name": "Re-Hash" },
				{ "id": "2", "name": "5/4" },
				{ "id": "3", "name": "Tomorrow Comes today" },
				{ "id": "4", "name": "New Genious(brother)" },
				{ "id": "5", "name": "Clint Eastwood" },
				{ "id": "6", "name": "Man Research(clapper)" },
				{ "id": "7", "name": "Punk" },
				{ "id": "8", "name": "Sound Check(Gravity)" },
				{ "id": "9", "name": "Double Bass" },
				{ "id": "10", "name": "Rock The House" },
				{ "id": "11", "name": "19-2000" },
				{ "id": "12", "name": "Latin Simone(que pasa contigo)" },
				{ "id": "13", "name": "StarShine" },
				{ "id": "14", "name": "Slow Country" }
]},
{"name":"G-Sides","id":"2","year":"2001","photo":"thumbnails/album2thumbnail.jpg","songs":[
				{ "id": "1", "name": "19-2000(soulchild remix)" },
				{ "id": "2", "name": "Dracula" },
				{ "id": "3", "name": "Rock the house(radio edit)" },
				{ "id": "4", "name": "The Sounder(edit)" },
				{ "id": "5", "name": "Faust" },
				{ "id": "6", "name": "Clint Eastwood - phi life cypher version" },
				{ "id": "7", "name": "Ghost Train" },
				{ "id": "8", "name": "Hip Albatross" },
				{ "id": "9", "name": "left hand suzuki method" },
				{ "id": "10", "name": "12D3" }
]},
{"name":"Laika Come Home","id":"3","year":"2002","photo":"thumbnails/album3thumbnail.jpg","songs":[
				{ "id": "1", "name": "19/2000(Jungle Fresh)" },
				{ "id": "2", "name": "slow country (strictly rubbadub)" },
				{ "id": "3", "name": "tomorrow comes today (bañana baby)" },
				{ "id": "4", "name": "man research (monkey packet)" },
				{ "id": "5", "name": "punk (de-punked)" },
				{ "id": "6", "name": "5/4 (p.45)" },
				{ "id": "7", "name": "starshine (dub 09)" },
				{ "id": "8", "name": "sound check (gravity) (crooked dub)" },
				{ "id": "9", "name": "new genius (brother) (mutant genius)" },
				{ "id": "10", "name": "re hash (come again)" },
				{ "id": "11", "name": "clint eastwood (a fistful of peanuts)" },
				{ "id": "12", "name": "lil' dub chefin' (album version)" }
]},
{"name":"Demon Days","id":"4","year":"2005","photo":"thumbnails/album4thumbnail.jpg","songs":[
				{ "id": "1", "name": "Intro" },
				{ "id": "2", "name": "Last Living Souls" },
				{ "id": "3", "name": "Kids with Guns" },
				{ "id": "4", "name": "O Green World" },
				{ "id": "5", "name": "Dirty Harry" },
				{ "id": "6", "name": "Feel Good Inc." },
				{ "id": "7", "name": "El Manana" },
				{ "id": "8", "name": "Every Planet We Reach is Dead" },
				{ "id": "9", "name": "November Has Come" },
				{ "id": "10", "name": "All Alone" },
				{ "id": "11", "name": "White Light" },
				{ "id": "12", "name": "Dare(radio edit)" },
				{ "id": "13", "name": "Fire Coming Out of the monkeys Head" },
				{ "id": "14", "name": "Don't Get Lost in Heaven" },
				{ "id": "15", "name": "Demon Days" },
				{ "id": "16", "name": "The Swagga" },
				{ "id": "17", "name": "Feel Good Inc" },
				{ "id": "18", "name": "Feel Good Inc - Animatics" },
				{ "id": "19", "name": "Feel Good Inc - Audio Commentary" },
				{ "id": "20", "name": "Gorillaz Talent Quest (G Bite Animation)" },
				{ "id": "21", "name": "Gorillaz On Set - G Bite Animation" }
]},
{"name":"D-Sides","id":"5","year":"2007","photo":"thumbnails/album5thumbnail.jpg","songs":[
				{ "id": "1", "name": "68 State" },
				{ "id": "2", "name": "People" },
				{ "id": "3", "name": "HongKingaton" },
				{ "id": "4", "name": "We Are Happy Landfill" },
				{ "id": "5", "name": "Hong Kong" },
				{ "id": "6", "name": "Highway(Under Construction)" },
				{ "id": "7", "name": "Rockit" },
				{ "id": "8", "name": "Bill Murray" },
				{ "id": "9", "name": "The Swagga" },
				{ "id": "10", "name": "Murdoc Is God" },
				{ "id": "11", "name": "Spitting out the Demons" },
				{ "id": "12", "name": "Don't Get Lost in Heaven (Original Demo)" },
				{ "id": "13", "name": "Stop the Dams" },
				{ "id": "14", "name": "DARE (DFA Remix)" },
				{ "id": "15", "name": "Feel Good Inc. (Stanton Warriors Remix)" },
				{ "id": "16", "name": "Kids with Guns (Jamie T's Turns to Monsters Mix)" },
				{ "id": "17", "name": "DARE (Soulwax Remix)" },
				{ "id": "18", "name": "Kids with Guns (Hot Chip Remix)" },
				{ "id": "19", "name": "El Mañana (Metronomy Remix)" },
				{ "id": "20", "name": "DARE (Junior Sanchez Remix)" },
				{ "id": "21", "name": "Dirty Harry (Schtung Chinese New Year Remix)" },
				{ "id": "22", "name": "Kids with Guns (Quiet Village Remix)" }
]},
{"name":"Plastic Beach","id":"6","year":"2010","photo":"thumbnails/album6thumbnail.jpg","songs":[
				{ "id": "1", "name": "Orchestral Intro" },
				{ "id": "2", "name": "Welcome to the World of the Plastic Beach" },
				{ "id": "3", "name": "White Flag" },
				{ "id": "4", "name": "Rhinestone Eyes" },
				{ "id": "5", "name": "Stylo" },
				{ "id": "6", "name": "Superfast Jellyfish" },
				{ "id": "7", "name": "Empire Ants" },
				{ "id": "8", "name": "Glitter Freeze" },
				{ "id": "9", "name": "Some Kind of Nature" },
				{ "id": "10", "name": "On Melancholy Hill" },
				{ "id": "11", "name": "Broken" },
				{ "id": "12", "name": "Sweepstakes" },
				{ "id": "13", "name": "Plastic Beach" },
				{ "id": "14", "name": "To Binge" },
				{ "id": "15", "name": "Colud of Unknowing" },
				{ "id": "16", "name": "Pirate Jet" }
]},
{"name":"The fall","id":"7","year":"2010","photo":"thumbnails/album7thumbnail.jpg","songs":[
				{ "id": "1", "name": "Phoner to Arizona" },
				{ "id": "2", "name": "Revolving Doors" },
				{ "id": "3", "name": "HillBilly Man" },
				{ "id": "4", "name": "Detroit" },
				{ "id": "5", "name": "Shy-town" },
				{ "id": "6", "name": "Little Pink Plastic Bags" },
				{ "id": "7", "name": "The Joplin Spider" },
				{ "id": "8", "name": "The Parish of Space Dust" },
				{ "id": "9", "name": "The Snake in Dallas" },
				{ "id": "10", "name": "Amarillo" },
				{ "id": "11", "name": "The Speak It Mountians" },
				{ "id": "12", "name": "Aspen Forest" },
				{ "id": "13", "name": "Bobby in Phoenix" },
				{ "id": "14", "name": "California & The Slipping of the Sun" },
				{ "id": "15", "name": "Seatlle Yodel" }
]},
{"name":"Humanz","id":"8","year":"2017","photo":"thumbnails/album8thumbnail.jpg","songs":[
				{ "id": "1", "name": "i switched my robot off" },
				{ "id": "2", "name": "Ascension" },
				{ "id": "3", "name": "Strobelite" },
				{ "id": "4", "name": "Saturnz Barz" },
				{ "id": "5", "name": "momentz" },
				{ "id": "6", "name": "interlude: the non-conformist oath" },
				{ "id": "7", "name": "submission" },
				{ "id": "8", "name": "charger" },
				{ "id": "9", "name": "interlude: elevator going up" },
				{ "id": "10", "name": "andromeda" },
				{ "id": "11", "name": "busted and blue" },
				{ "id": "12", "name": "interlude: talk radio" },
				{ "id": "13", "name": "carnival" },
				{ "id": "14", "name": "let me out" },
				{ "id": "15", "name": "interlude: penthouse" },
				{ "id": "16", "name": "sex murder party" },
				{ "id": "17", "name": "she’s my collar" },
				{ "id": "18", "name": "interlude: the elephant" },
				{ "id": "19", "name": "hallelujah money" },
				{ "id": "20", "name": "we got the power" }
]},
{"name":"The Now Now","id":"9","year":"2018","photo":"thumbnails/album9thumbnail.jpg","songs":[
				{ "id": "1", "name": "Humility" },
				{ "id": "2", "name": "Tranz" },
				{ "id": "3", "name": "Hollywood" },
				{ "id": "4", "name": "Kansas" },
				{ "id": "5", "name": "Sorcererz" },
				{ "id": "6", "name": "Idaho" },
				{ "id": "7", "name": "Lake Zurich" },
				{ "id": "8", "name": "Magic City" },
				{ "id": "9", "name": "Fire Flies" },
				{ "id": "10", "name": "One Percent" },
				{ "id": "11", "name": "Souk Eye" }
			]
		}
	],
};

var dept = {
	title: "Custom Albums",
	employee :[
        {
            'albumname':"Demon Days",
		    'firstname': "Fred",
	        'lastname': "Bloggs",
	        'songtitle':'Feel Good Inc',
			'genre':"HipHop",
			'bpm':"139",
	        'email':'fbloggs@gmail.com'
        },
        {
            'albumname':"G-sides",
			'firstname': "Katy",
		    'lastname': "Malone",
		    'songtitle':'Dracula',
			'genre':"HipHop",
			'bpm':"121",
		    'email':'kmalone@gmail.com'
	    }
  ]
  };